### ISSUE TITLE
Error in hardware/xmegaduino/boards.txt

### ISSUE THREAD

**Issue by wayoda** [Xmegaduino/Xmegaduino#11]
Hi
in file `hardware/xmegaduino/boards.txt` on line 197

```
#akafuino.bootloader.lock_bits=0x3F

 FUSE BITS
# fuse0: JTAGUSERID
# fuse1: WDWP=0xF WDP=0xF
```

A comment delimiter is missing in front of `FUSE BITS`

**Comment by karlbackstrom** [comment]
Ah, well spotted. Will fix it.
