### ISSUE TITLE
EEPROM Issues

### ISSUE THREAD

**Issue by RemcoMagielse** [Xmegaduino/Xmegaduino#16]
Dear All,

I've tried to include the eeprom library, but the compiler throws a lot of erros when I try to compile for the Akafuino X.
Any suggestions on how to fix this?

Errors included:
In file included from /Applications/Arduino.app/Contents/Resources/Java/libraries/EEPROM/EEPROM.cpp:24:
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:141:4: error: #error "Unknown EEPROM register(s) location."
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:197:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:201:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:215:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:217:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:309:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:320:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:322:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:333:1: error: invalid suffix "x__EEPROM_REG_LOCATIONS__" on integer constant
In file included from /Applications/Arduino.app/Contents/Resources/Java/libraries/EEPROM/EEPROM.cpp:24:
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h: In function 'uint8_t eeprom_read_byte(const uint8_t_)':
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:197: error: 'EEWE' was not declared in this scope
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:216: error: 'EERE' was not declared in this scope
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h: In function 'void eeprom_write_byte(uint8_t_, uint8_t)':
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:309: error: 'EEWE' was not declared in this scope
/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../lib/gcc/avr/4.3.3/../../../../avr/include/avr/eeprom.h:335: error: 'EEMWE' was not declared in this scope

**Comment by karlbackstrom** [comment]
Are you running Beta3?
It was supposed to be fixed here: https://github.com/akafugu/Xmegaduino/issues/6.

**Comment by RemcoMagielse** [comment]
I was under the impression I was, but apparantly I was not.
This has fixed the issue.
Thanks and sorry for the inconvenience.

**Comment by karlbackstrom** [comment]
No problem, happy the problem is resolved.
