### ISSUE TITLE
Issue when compiling on mac OSX

### ISSUE THREAD

**Issue by RemcoMagielse** [Xmegaduino/Xmegaduino#17]
Dear All,

Just downloaded the newest beta release 4.
Tried uploading to an Akafuino X board, but this threw the following error when compiling:

dyld: Library not loaded: /usr/local/lib/libmpc.2.dylib
  Referenced from: /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/../libexec/gcc/avr/4.5.1/cc1plus
  Reason: image not found
avr-g++: Internal error: Trace/BPT trap (program cc1plus)
Please submit a full bug report.
See http://gcc.gnu.org/bugs.html for instructions.

Will go back to beta 3 now, please let me know how I can resolve this.

Regards,

Remco

**Comment by karlbackstrom** [comment]
Thanks for the bugreport, will look into it.

**Comment by karlbackstrom** [comment]
Currently uploading a beta4b with a updated toolchain.
