### ISSUE TITLE
Xmegaduino Arduino IDE does not start or freezes on windows 7 64 bit

### ISSUE THREAD

**Issue by 3dotter** [Xmegaduino/Xmegaduino#18]
Xmegaduino Arduino IDE does not start or freezes on windows 7 64 bit. Please have a look at issues.

**Comment by karlbackstrom** [comment]
Hi 3dotter,

sorry to hear that you have problem with Xmegaduino.
Just to rule a few things out, can you try to install the regular Arduino 1.0.1 from here http://arduino.cc/en/Main/Software and make sure you can run it on your system?

**Comment by 3dotter** [comment]
Hi Karl.

Yes, I will do that.

Best wishes,

Addy

Van: Karl Backström [mailto:notifications@github.com] 
Verzonden: 24 September 2012 13:52
Aan: akafugu/Xmegaduino
CC: 3dotter
Onderwerp: Re: [Xmegaduino] Xmegaduino Arduino IDE does not start or freezes on windows 7 64 bit (#18)

Hi Addy,

sorry to hear that you have problem with Xmegaduino.
Just to rule a few things out, can you try to install the regular Arduino 1.0.1 from here http://arduino.cc/en/Main/Software and make sure you can run it on your system?

—
Reply to this email directly or view it on GitHub https://github.com/akafugu/Xmegaduino/issues/18#issuecomment-8816236 . 

  https://github.com/notifications/beacon/wUaJTV_HtgTj0Uw_5wABnhvy8nlDqm_zIKoqA_qzRQe_T7adSWXeZr9xKvZ6GVnQ.gif

**Comment by karlbackstrom** [comment]
Closing for now.
