### ISSUE TITLE
SD library examples do not compile

### ISSUE THREAD

**Issue by srini91** [Xmegaduino/Xmegaduino#19]
When compiling any of the SD library examples for the Akafuino X board, there are a ton of compilation errors.  The errors are:

.../SD/utility/Sd2PinMap.h:285:5: error: 'DDRD' was not declared in this scope
.../SD/utility/Sd2PinMap.h:285:12: error: 'PIND' was not declared in this scope

and so on...

**Comment by karlbackstrom** [comment]
Hi srini91,

yes, the SD library is currently not ported to Xmegaduino yet. Sorry.

The Sd2PinMap.h file is for using Software SPI and mapping pins to ports to be able to do fast bit flipping. Not quite sure if we should go with hardware SPI or software SPI.
The hardware SPI on Xmega is really simple to implement (see the already ported /libraries/SPI/)

**Comment by karlbackstrom** [comment]
The SD library in 1.5.x has been rewritten to use SPI library. Closing
