### ISSUE TITLE
bootloader on ATXmega128a3

### ISSUE THREAD

**Issue by mogenson** [Xmegaduino/Xmegaduino#20]
Hi,

Would the bootloader for the ATXmega128a1 work on an ATXmega128a3?  Also, would I even need a bootloader if I generate HEX files with the Xmegaduino IDE and upload them over PDI?

Thanks

**Comment by karlbackstrom** [comment]
Hi,

you probably need to recompile to get it running on ATXmega128a3. Check the bootloader project here:
https://github.com/alexforencich/xboot

Yes, if you use PDI to upload you do not need a bootloader, the bootloader is for uploading via serial or TWI/I2C.

**Comment by mogenson** [comment]
Great.  Thanks for the information.

**Comment by hyteoo** [comment]
Hi
did you manage to get it running?
I am also trying to get the bootloader running on an ATXmega128a3u however no matter what settings I change, it behaves the same - toggles PE7 pin continuously and the USART is unresponsive
