### ISSUE TITLE
Blink example doesn't work on atmel xmega128a1 xplain board

### ISSUE THREAD

**Issue by al1ta** [Xmegaduino/Xmegaduino#21]
compiling and uploading the Blink example went ok but no leds are tuned on xplain board.
I've changed the pin to 17 as shown on http://code.google.com/p/xmegaduino/wiki/XplainPinMapping and it is expected to turn blinking the led 1

could it be a bug ?

I'm using these settings:
-  programmer: the mkii programmer (on at90usb1297 by xplain bridge)  
- board: xplain on pdi

this is the simple code

/*
  Blink
  Turns on an LED on for one second, then off for one second, repeatedly.

  This example code is in the public domain.
 */

void setup() {  
  // initialize the digital pin as an output.
  // Pin 13 has an LED connected on most Arduino boards:
  pinMode(17, OUTPUT);  
}

void loop() {
  digitalWrite(17, HIGH);   // set the LED on
  delay(1000);              // wait for a second
  digitalWrite(17, LOW);    // set the LED off
  delay(1000);              // wait for a second
}

**Comment by karlbackstrom** [comment]
Hi,

the information on Google Code seems to be old and outdated, the correct mapping for XPlain is
Arduino - Port
0-7 PORTA
8-15 PORTB
16-23 PORTC
24-31 PORTD
etc.

Hope this helps.

**Comment by al1ta** [comment]
it works!! 

Thank you ...

**Comment by karlbackstrom** [comment]
Great!
