### ISSUE TITLE
arduino.exe shows splash screen and then exits

### ISSUE THREAD

**Issue by per-magnusson** [Xmegaduino/Xmegaduino#22]
I just downloaded and compiled Xmegaduino on Windows 7 64-bit. The build succeeds, but when I try to start ardunio.exe, either through "ant run", double clicking on the exe file or running it from a cmd window, I just get the splash screen for a few seconds and then the program terminates. 

In cmd "echo %ERRORLEVEL%" prints 1.

The normal Arduino 1.0.2 runs fine as downloaded from http://www.arduino.cc/en/Main/Software works fine on this machine.

Any ideas on what is wrong?

**Comment by per-magnusson** [comment]
I should maybe mention that I have no board plugged in as I wanted to try out the software before I buy a board. This seems to work fine for the normal Arduino software, but the instructions at http://www.akafugu.jp/posts/products/akafuino_x/usage/ mention that the board should be plugged in before starting the software. I do not know if this is important or not.

**Comment by karlbackstrom** [comment]
Hi Per,

sorry for the late reply.

About having a board connected, this is mainly to make sure you have the drivers for the board installed (FTDI drivers, same as older Arduino (before UNO))

I have successfully used Xmegaduino on Windows 7 64-bit, could you download the pre-compiled package from this link and test: https://github.com/akafugu/Xmegaduino/downloads

**Comment by per-magnusson** [comment]
Hi Karl,

Thanks for replying. I Downloaded the precompiled version using your link and that starts fine. I am able to compile a sketch. (I am new to Github and I cannot find that download link anywhere around here except in your message.)

I have also got an Xmega-A1 Xplained board now. I guess the next step is to figure out how to get the LUFA USB code into the Xplained board to start using it from Xmegaduino.

**Comment by karlbackstrom** [comment]
Hi Per,

great to hear that it worked for you. If you figure out why your compilation didn't work (perhaps a missing library of some sort?) it would be great to hear.

They seem to have moved around things on github again, but there is a link in the README.mk (https://github.com/akafugu/Xmegaduino#installation), have to figure out how to make it more visible, suggestions are appreciated.

Cool, let me know how it goes with your board.

Closing this issue for now.
