### ISSUE TITLE
Bootloader for Xmega 32A4U

### ISSUE THREAD

**Issue by sebastianstoecklin** [Xmegaduino/Xmegaduino#23]
I just wanted to use the Xmegaduino fork on my self-made Xmega board with a 32A4U chip. Since it is quite similar to the 32A4 (except for the built-in USB?!), I just tried to use the Akafuino X bootloader for the 32A4, but without success. Uploading a sketch via USB fails (upload progress is really slow and finishes by showing the message "avrdude: error: buffered memory access not supported. Maybe it isn't a butterfly/AVR109 but a AVR910 device?").
The board's layout concerning the serial connection is the same as the Akafuino's.The Xmega and the FT232R chip work fine in general. The bootloader was uploaded using Atmel Studio 6 and an AVRISP MK2 clone. Additionally, the fuses were set according to the boards.txt file in the hardware/xmegaduino-folder.

Any suggestions?

**Comment by sebastianstoecklin** [comment]
Just created another Xboot bootloader - somehow, Xboot gave me errors while setting the device to atxmega32a4u, so I made it for atxmega32a4... It works in general (a test sketch printing "hello" on the serial interface works fine), but avrdude continues on throwing error messages:

Connecting to programmer: .
Found programmer: Id = "XBoot++"; type = S
    Software Version = 1.7; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=256 bytes.

Programmer supports the following devices:
    Device code: 0x7b

avrdude: verification error, first mismatch at byte 0x0000
         0x0c != 0xff
avrdude: verification error; content mismatch

Btw: Using a separate install of avrdude doesn't result in any failures... strange.

**Comment by karlbackstrom** [comment]
I am not quite sure how to read your bug report, you say that it works now but you still get an error? Have you tried to upload a completely different sketch and verified that it is indeed updating it correctly?

I am no expert on the bootloader so for more help on the bootloader and possible issues with it, please see the xboot project where Alex (the author of XBoot) can perhaps answer your question.
https://github.com/alexforencich/xboot

**Comment by sebastianstoecklin** [comment]
You're right! The main concern was that the given bootloader didn't work at all, but this kind of problem is solved... So please consider this issue to be closed... :-)
The problem described in my second post seems to be related with bootloader and avrdude stuff, which isn't a bug of the Xmegaduino software - I just hoped anyone already figured out a 100% working solution for the 32A4U.
