### ISSUE TITLE
Serial on a Custom XMega Board

### ISSUE THREAD

**Issue by lthiery** [Xmegaduino/Xmegaduino#25]
I have never really messed with the Arduino core before, so forgive me in advance if I'm overlooking something obvious.

I have my own ATXMega board that transmits serial just fine with this code uploaded:

``` c
void setup() { 
  PORTC.DIR |= (1<<3) | (1<<0);
  PORTC.OUT |= (1<<3);          
  USARTC0.BAUDCTRLA = 207; // 9600b  (BSCALE=207,BSEL=0)

  USARTC0.CTRLB = USART_TXEN_bm | USART_RXEN_bm; // enable tx and rx on USART
}

void loop() {
  UsartWriteChar(0x5); // write char
}

void UsartWriteChar(unsigned char data)
{
    USARTC0.DATA = data;   //transmit data
    if(!(USARTC0.STATUS&USART_DREIF_bm))
        while(!(USARTC0.STATUS & USART_TXCIF_bm)); // wait for TX complete
    USARTC0.STATUS |= USART_TXCIF_bm;  // clear TX interrupt flag
};
```

However, when I try the following, nothing happens:

``` c
void setup() {
  Serial.begin(9600);
}

void loop() {
  Serial.print(0x5);
}
```

So far, I am pretending to be the Akafuino variant and I told the boards file that I have an atxmega128a3 - which appears to work fine since the first snippet of code was uploaded using the IDE.

I have investigated the HardwareSerial file to no avail. Things break as soon as I try to include any Serial objects. Any leads?

**Comment by lthiery** [comment]
I have learned that only defining one of the serial ports in serial_init.cpp (in "hardware/xmegaduino/variants/myvariant") allows that one serial port to work. It does not matter which one, only that I define only one. 

I still want to be able to define more than one Serial port for my variant but this is an interesting clue...

**Comment by karlbackstrom** [comment]
Hi Louis,

thank you for your bug report.
I rechecked on atxmega32a4 and it seems to work here at least.

You said that only defining one serial port works. Could you paste your setup here?

I have scanned through the HardwareSerial.cpp file and the only suspect function I can find (that might also explain other lockups) is this one:

``` c
size_t HardwareSerial::write(uint8_t c)
{
  while ( !(_usart->STATUS & USART_DREIF_bm) );
  _usart->DATA = c;

  return 1;
}
```

This code is from before I started maintain the project. Could you try by replacing the function with a modified version of yours:

``` c
size_t HardwareSerial::write(uint8_t c)
{
  _usart->DATA = c;   //transmit data
  if(!(_usart->STATUS & USART_DREIF_bm))
    while(!(_usart->STATUS & USART_TXCIF_bm)); // wait for TX complete
  _usart->STATUS |= USART_TXCIF_bm;  // clear TX interrupt flag

  return 1;
}
```

**Comment by lthiery** [comment]
Hi Karl

Thanks for helping out. To be more explicit, yesterday I found that this works as the serial_init.cpp file:

``` c
// Preinstantiate Objects //////////////////////////////////////////////////////

#define SERIAL_DEFINE(name, usart_port, port_nr) \
ring_buffer name##rx_buffer = { { 0 }, 0, 0 }; \
ISR(USART##usart_port##port_nr##_RXC_vect) \
{ \
  unsigned char c = USART##usart_port##port_nr.DATA; \
  store_char(c, &name##rx_buffer); \
} \
HardwareSerial name (&name##rx_buffer, &USART##usart_port##port_nr, &PORT##usart_port, (port_nr ? PIN6_bm : PIN2_bm), (port_nr ? PIN7_bm : PIN3_bm));

SERIAL_DEFINE(Serial, E, 0);
//SERIAL_DEFINE(Serial1, E, 1);
//SERIAL_DEFINE(Serial2, D, 0);
//SERIAL_DEFINE(Serial3, D, 1);
//SERIAL_DEFINE(Serial4, C, 0);
```

but if I uncomment any of the other serial objects, none of the serial ports work. I cycled through all the ports as the only serial object and they all worked fine. I also checked to see if maybe the last port being defined worked and that did not. Finally, I tried to eliminate the ISR to see if multiple Serial objects without the ISR would not conflict, but the failure was identical.

I was hoping the Serial constructor would contain something getting redefined or something, but it seems to be a non-event:

``` c
HardwareSerial::HardwareSerial(
  ring_buffer *rx_buffer,
  USART_t     *usart,
  PORT_t      *port,
  uint8_t      in_bm,
  uint8_t      out_bm)
{
  this->_rx_buffer = rx_buffer;
  this->_usart     = usart;
  this->_port      = port;
  this->_in_bm     = in_bm;
  this->_out_bm    = out_bm;
}
```

Since things worked fine on your atxmega32a4, it suggests that either there is something different about the atxmega128a3 (unlikely) or that there is something wrong with my hardware. The fact that one Serial port works at a time however makes me think that the hardware is not the issue though. Hmm...

EDIT:
I also tried the code modification that you suggested but it did not solve the problem. And for good measure I made sure that I could run two Serial comms with my code and it was fine. It's puzzling that simply creating multiple Serial instances makes it fail...

**Comment by karlbackstrom** [comment]
Hi Louis,

could you see when the device crash/hangs, if it is in initialization or when trying to write to the UART? (Eg by flashing leds)

I don't think there is anything wrong with your board/uC, as some more users have had problems with serial on A1, it looks like a problem with xmegaduino.

By the way, you are compiling your testcode with the compiler from xmegaduino, right?

**Comment by lthiery** [comment]
Hi Karl,

I am on 64-bit Linux (Ubuntu 12.04) and am compiling and uploading the code using the xmegaduino IDE.

I tried the sketch at the end of this post to find out when it hangs. There is absolutely no output on the pins (measured with scope) when I have more than one serial object defined in serial_init.cpp. Output was as expected when only one Serial object was defined.

I will try things over in Windows 7 just to see.

``` c
bool state = true;

void setup(){
  pinMode(3,OUTPUT);
  digitalWrite(3,HIGH);
  delay(1000);

  Serial.begin(9600);

  digitalWrite(3,LOW);
  delay(1000);
}

void loop(){
  if(state){
    digitalWrite(3, LOW);
    state=false;
  }
  else{
    digitalWrite(3, HIGH);
    state=true;
  }
  Serial.write(0xFF);
  delay(500);
}
```

**Comment by karlbackstrom** [comment]
Thank you for checking.

> There is absolutely no output on the pins (measured with scope) when I have more than one serial object defined in serial_init.cpp. Output was as expected when only one Serial object was defined.

On pin 3? In that case I assume it crashes before setup() is ran, probably during initialization of the Serial object.

One more thing to try, could you try to only define Serial1 and not Serial?

**Comment by lthiery** [comment]
1) Attempts in Windows gave same results.

2) Only defining Serial1 in the previously posted debug sketch does not change results on pin 3 or on Serial output

**Comment by karlbackstrom** [comment]
Thanks.

So to summarize:
- Only Serial defined: OK
- Only Serial1 defined: NG
- Serial + all/any other SerialX defined: NG

I assume that if you change ports on Serial (to say UARTD0) the code is running?

**Comment by lthiery** [comment]
Sorry - I misunderstood the Serial1 request.

Any single Serial defined, regardless of SerialX or PortX: OK (ie: only Serial1 defined: OK)

More than one Serial defined, regardless of naming, port, or number on port: NG

**Comment by lthiery** [comment]
I kept running into this as a recurring bug that could be summarized as: "Global constructors crash the code". I found some issues from a few years ago on avr-gcc so I deleted the avr folder in the Xmegaduino distribution. The IDE now relies on my systems avr-gcc which I think I just got some sudo apt-get on Ubuntu 12.04. 

This seems to have resolved it for now :)

**Comment by karlbackstrom** [comment]
Thanks for all your help.
This also explains why I haven't seen this problem as I am mainly using Win and Mac version.

Will look into updating the compiler to the one Atmel release.
