### ISSUE TITLE
ADC Returns -1

### ISSUE THREAD

**Issue by lthiery** [Xmegaduino/Xmegaduino#27]
Just tried analogRead(A0) for the first time. I'm getting -1 back. I wrote a low level code that proves that my ADCs are OK:

```
void setup(){
  Serial.begin(57600);
  PORTB.DIR = 0;    // configure PORTB as input
  ADCB.CTRLA |= 0x1;    // enable adc
  ADCB.CTRLB = ADC_RESOLUTION_12BIT_gc;     // 12 bit conversion
  ADCB.REFCTRL = 0b010;     // use AREF
  ADCB.PRESCALER = ADC_PRESCALER_DIV8_gc;   // peripheral clk/8 (2MHz/16=250kHz)
  ADCB.CH0.CTRL = ADC_CH_INPUTMODE_SINGLEENDED_gc;  // single ended
  ADCB.CH0.MUXCTRL = ADC_CH_MUXPOS_PIN1_gc;     // PORTB:1
}

void loop(){
  ADCB.CH0.CTRL |= ADC_CH_START_bm; // start conversion on channel 0
  while(!ADCB.CH0.INTFLAGS);
  uint16_t result = ADCB.CH0RES;
  Serial.println((result/4095.0*3.3));
  delay(1000);
}
```

Note: I'm taking PB1 on purpose since I'm using it to measure my battery level. 

I noticed on the datasheet that there is no option to take VCC directly as AREF. I wired VCC into AREF for now but from now but I think taking AREF=VCC/2 by setting the register that way would be a good default.

Anyway, I will dig into the code later but I wanted to post to see if there were any gotchas anyone could alert me to.

**Comment by lthiery** [comment]
OK, so all the analogRead happens in wiring_analog.c in the xmegaduino core. The function analogRead returns analogRead12(pin)>>2 (so that we are still compatible with Wiring convention of 10 bits I assume) so I go over to analogRead12.

This is the offending piece of code:

```
#if defined(ADCB) //Atxmega128a1 has 2 8 channel ADCs
    if ( pin < 8 ) {
        adc = &ADCA;
    } else if ( pin < 16 ) {
        adc = &ADCB;
        pin -= 8;
#else            //Atxmega32a4 has 1 12 channel ADC
    if ( pin < 12 ) {
        adc = &ADCA;
#endif
    } else {
        return -1;
    }
}
```

What I don't understand is that I took the Akafuino pin mappings where A0-A5 are defined with pins 22-28. How does this function work for you guys? My stupid fix was to append the code above with: `pin-=21;` That works as long as everyone knows to do start your analog pins at 22. 

Is there a more elegant way to do this? How does this function even work with Akafuino?

**Comment by lthiery** [comment]
Also, to answer my own questions, it appears that VCC/2 is the reference which I am happy with :+1:

**Comment by karlbackstrom** [comment]
Thanks for your debugging.
I am not quite sure which question I should answer here :)
But I think you are free to choose any value for pin-=21 as long as it makes sense with what is in your variants file.

If we want to support a bigger range of different processors it might be worth looking into making these things settings in the variants file.

**Comment by karlbackstrom** [comment]
Can this be closed?
