### ISSUE TITLE
Support for AVR XMEGA128A4U

### ISSUE THREAD

**Issue by maziarzamani** [Xmegaduino/Xmegaduino#38]
I understand that this IDE supports XMEGA128A1, but how much would it require to support A4U as well?

Cheers.

**Comment by ms34me** [comment]
I am curious about this as well. I am about to start a project that uses the A4U, and I'm wondering how much work that is going to be.

**Comment by karlbackstrom** [comment]
The same answer as #36 is valid here.

Most parts are already in there, you will need to specify a new board in boards.txt(1) and make a new directory and files in variants/ (2).

There is currently no support for built-in usb on the new U chip, so pull-requsts for that feature is appreciated.

(1) https://github.com/akafugu/Xmegaduino/blob/xmegaduino/hardware/arduino/xmega/boards.txt
(2) https://github.com/akafugu/Xmegaduino/tree/xmegaduino/hardware/arduino/xmega/variants

**Comment by ms34me** [comment]
I can attempt to do this, but I will probably need help ;)

**Comment by maziarzamani** [comment]
What about the bootloader?

**Comment by karlbackstrom** [comment]
Sorry for the late reply.

About the bootloader:
I would suggest avr-xboot (1), it is a robust serial bootloader, unfortunately it currently does not work with USB port (only UART, I2C and SPI).

For an USB bootloader I don't know of any existing ones except the flip one from Atmel. The Atmel bootloader has a couple of problems though:
1. You can get a pre-compiled version of the bootloader, but if you want to change the condition when it is entering the bootloader you need to compile it yourself. They use a commercial compiler that is free for up to 4kB binaries. The bootloader for chip with more than 64kB flash has a 8kB bootloader and can thus not be compiled with the free version.
2. "flip2" programmer was added to Avrdude 6.1, current Arduino 1.6.x and Xmegaduino is distributed with Avrdude 6.0.1.

Hope this answers your questions.

(1) https://github.com/alexforencich/xboot

**Comment by maziarzamani** [comment]
@karlbackstrom I successfully flashed the chip with xboot! But setting up the variants seems a little fuzzy to me right now (pins mapping).

**Comment by karlbackstrom** [comment]
The pin mapping for "variants/akafuino/ is for our board Akafuino X.
![Xmegaduino](http://www.akafugu.jp/images/products/akafuino-x/akafuino-x-2.jpg)
[http://www.akafugu.jp/posts/products/akafuino_x/resources/](http://www.akafugu.jp/posts/products/akafuino_x/resources/)

If you check the picture/description and compare them to variants/akafuino maybe things gets more clear?

**Comment by maziarzamani** [comment]
Almost makes sense, almost. What seems very strange to me is that the digital I/O for Port-C begins from PC2, but in the datasheet PC2 is on pin 12, while PC0 is on 10. So why is it that the first digital pin is PC2 and not PC0?

**Comment by karlbackstrom** [comment]
You mean for D0? It was to be compatible with Arduino board and have first
serial port on D0/D1.

On Tuesday, January 6, 2015, maziarzamani notifications@github.com wrote:

> Almost makes sense, almost. What seems very strange to me is that the
> digital I/O for Port-C begins from PC2, but in the datasheet PC2 is on pin
> 12, while PC0 is on 10. So why is it that the first digital pin is PC2 and
> not PC0?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akafugu/Xmegaduino/issues/38#issuecomment-68847794.

## 

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu
